#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.wechat.message.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    #mysql日志打印到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/message
    username: root
    password: leeyf100%
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
#logging:
#  level:
#    com:
#      wechat:
#        WARN: DEBUG
#        INFO: DEBUG
#        ERROR: DEBUG

